### ISSUE TITLE
section: GALLERY

### ISSUE THREAD

**Issue by monroemann** [monroemann/breakdiving#12]
I'd like to show off the photos of our events here.  On the current site, it's very messy.  Small thumbnails that expand upon hovering would be a lot cleaner. I want to be sure everything is accessible to the blind, so we need to keep that in mind with the photo stuff, i.e. proper aria and alt tags where needed throughout

**Comment by waywho** [comment]
I am wondering if this is a section where you would need some kind of photo management system (database or other options). It is very time consuming to code individual photos into a gallery grid, and it would be time consuming to update it. I am thinking that potentially if you have an instagram feed, that can be used as the photo management system instead of a database. In the future you can also have people add to the gallery automatically by hastagging their photos. 

Also I think hover to expand is a bit taxing on computer power and from user experience point of view might be fun to begin with but annoying after awhile. I am wondering if we could do what you are doing right now, click to a greyed out gallery instead?
